CREATE DATABASE CLARAVISAO;

USE CLARAVISAO;

CREATE TABLE USUARIOS(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	SOBRENOME VARCHAR(100) NOT NULL,
	USERNAME VARCHAR(25) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	SENHA VARCHAR(80) NOT NULL,
	ADM INT(1) NOT NULL DEFAULT 0, --- 0 não é adm, 1 é adm 
	TELEFONE VARCHAR(20),
	IMAGEM VARCHAR(255) DEFAULT 'user_padrao.jpg'
);

CREATE TABLE CLIENTES(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CLIENTE VARCHAR(255) NOT NULL,
	PROFISSAO VARCHAR(100),
	DATA_NASCIMENTO DATE NOT NULL,
	TELEFONE_1 VARCHAR(18) NOT NULL,
	TELEFONE_2 VARCHAR(18),
	CIDADE VARCHAR(60) DEFAULT 'Descalvado',
	FOTO VARCHAR(150) DEFAULT 'user_padrao.jpg'
);

CREATE TABLE ORCAMENTOS(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CLIENTE INT NOT NULL,
	VENDEDOR VARCHAR(255),
	VENDEDOR_ID INT,
	DATA_CRIACAO DATE,
	DATA_ENTREGA DATE,
	OS VARCHAR(10),
	FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(ID),
	-- Longe
	LONGE_OD_ESF VARCHAR(8),
	LONGE_OD_CIL VARCHAR(8),
	LONGE_OD_EIXO VARCHAR(8),
	LONGE_OD_ADICAO VARCHAR(8),
	LONGE_OD_DNP VARCHAR(8),
	LONGE_OD_ALTURA VARCHAR(8),
	LONGE_OE_ESF VARCHAR(8),
	LONGE_OE_CIL VARCHAR(8),
	LONGE_OE_EIXO VARCHAR(8),
	LONGE_OE_ADICAO VARCHAR(8),
	LONGE_OE_DNP VARCHAR(8),
	LONGE_OE_ALTURA VARCHAR(8),
	-- perto
	PERTO_OD_ESF VARCHAR(8),
	PERTO_OD_CIL VARCHAR(8),
	PERTO_OD_EIXO VARCHAR(8),
	PERTO_OD_ADICAO VARCHAR(8),
	PERTO_OD_DNP VARCHAR(8),
	PERTO_OD_ALTURA VARCHAR(8),
	PERTO_OE_ESF VARCHAR(8),
	PERTO_OE_CIL VARCHAR(8),
	PERTO_OE_EIXO VARCHAR(8),
	PERTO_OE_ADICAO VARCHAR(8),
	PERTO_OE_DNP VARCHAR(8),
	PERTO_OE_ALTURA VARCHAR(8),
	-- MEDIA
	MEDIA_OD_ESF VARCHAR(8),
	MEDIA_OD_CIL VARCHAR(8),
	MEDIA_OD_EIXO VARCHAR(8),
	MEDIA_OD_ADICAO VARCHAR(8),
	MEDIA_OD_DNP VARCHAR(8),
	MEDIA_OD_ALTURA VARCHAR(8),
	MEDIA_OE_ESF VARCHAR(8),
	MEDIA_OE_CIL VARCHAR(8),
	MEDIA_OE_EIXO VARCHAR(8),
	MEDIA_OE_ADICAO VARCHAR(8),
	MEDIA_OE_DNP VARCHAR(8),
	MEDIA_OE_ALTURA VARCHAR(8),

	OFTALMOLOGISTA VARCHAR(255),
	ARMACAO VARCHAR(255),
	ARMACAO_REFERENCIA VARCHAR(255),
	ARMACAO_PRECO VARCHAR(15),
	ARMACAO_TIPO VARCHAR(20),
	LENTE VARCHAR(255),
	LENTE_PRECO VARCHAR(15),
	OBSERVACAO TEXT,
	LABORATORIO VARCHAR(200),
	PONTE_ARO VARCHAR(10),
	DIAG_MAIOR VARCHAR(10),
	VERTICAL VARCHAR(10),

	SUBTOTAL VARCHAR(15),
	DESCONTO VARCHAR(15),
	TOTAL VARCHAR(15),
	FORMA_PAG VARCHAR(30),
	NUM_PARCELAS VARCHAR(3),
	OBSERVACAO_2 TEXT
);

CREATE TABLE TEMPEMAIL(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TEMP_LINK VARCHAR(255) NOT NULL,
	EXPIRA TIMESTAMP NOT NULL,
	ID_ACCOUNT INT,
	FOREIGN KEY (ID_ACCOUNT) REFERENCES USUARIOS(ID)
);

CREATE TABLE SITE_SETTINGS(
	SETTING_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	ATRIBUTO VARCHAR(75) NOT NULL,
	VALUE1 VARCHAR(255) DEFAULT 'NULL',
	VALUE2 VARCHAR(255) DEFAULT 'NULL',
	VALUE3 VARCHAR(255) DEFAULT 'NULL',
	VALUE4 VARCHAR(255) DEFAULT 'NULL',
	VALUE5 VARCHAR(255) DEFAULT 'NULL',
	VALUE6 VARCHAR(255) DEFAULT 'NULL'
);


INSERT INTO USUARIOS(NOME, SOBRENOME, USERNAME, EMAIL, SENHA, ADM, TELEFONE) VALUES ('Admin', 'Admin', 'admin', 'admin@admin.com', '$2y$10$OpTJpSSwmuhcMygfKg4DG.I1z/J6rtUU9sRD53BLOwB8hH.M4vnd2', 0, '12345');